version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    assignees:
      - "fabiankachlock"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
